const fs = require('fs');
const content = fs.readFileSync('./server/store.ts', 'utf8');

const extraLeads = `,
  {
    id: 'lead_108',
    name: 'Aisha Mehta',
    email: 'aisha@techwave.io',
    phone: '+91 98765 43210',
    company: 'TechWave Solutions',
    service: 'full_stack_build',
    budget: 55000,
    status: 'qualified',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 85,
    source: 'Referral',
    notesCount: 1,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_109',
    name: 'Ravi Teja',
    email: 'ravi@krishifarms.in',
    phone: '+91 91234 56789',
    company: 'Krishi AgriTech',
    service: 'web_dev',
    budget: 32000,
    status: 'qualified',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 75,
    source: 'Inbound Contact',
    notesCount: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_110',
    name: 'Sunil Gavaskar',
    email: 'sunil@pitchperfect.io',
    phone: '+44 20 8123 4567',
    company: 'Pitch Perfect',
    service: 'shopify_dev',
    budget: 70000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 90,
    source: 'Public Web Capture',
    notesCount: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_111',
    name: 'Tara Singh',
    email: 'tara@boutiquehotels.in',
    phone: '+91 88888 99999',
    company: 'Heritage Stays',
    service: 'performance_marketing',
    budget: 15000,
    status: 'contacted',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 65,
    source: 'LinkedIn Outbound',
    notesCount: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_112',
    name: 'Suresh Raina',
    email: 'suresh@athleticgear.com',
    phone: '+1 (555) 345-6789',
    company: 'Athletic Gear Pro',
    service: 'cro_audit',
    budget: 25000,
    status: 'discovery',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 72,
    source: 'Event Booth',
    notesCount: 2,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_113',
    name: 'Smriti Mandhana',
    email: 'smriti@womeninbiz.org',
    phone: '+91 99999 11111',
    company: 'WIB Network',
    service: 'web_dev',
    budget: 40000,
    status: 'proposal',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 82,
    source: 'Referral',
    notesCount: 3,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_114',
    name: 'Prakash Raj',
    email: 'prakash@cinemaarts.co',
    phone: '+44 7700 900123',
    company: 'Cinema Arts Studio',
    service: 'shopify_dev',
    budget: 28000,
    status: 'negotiation',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 78,
    source: 'Inbound Contact',
    notesCount: 4,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_115',
    name: 'Divya Bharti',
    email: 'divya@glamourmag.in',
    phone: '+91 77777 66666',
    company: 'Glamour Magazine',
    service: 'full_stack_build',
    budget: 90000,
    status: 'won',
    assignedToId: 'usr_admin_1',
    assignedToName: 'Priya Sharma',
    score: 99,
    source: 'Referral',
    notesCount: 5,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_116',
    name: 'M.S. Dhoni',
    email: 'mahi@ranchifarms.com',
    phone: '+91 81818 81818',
    company: 'Ranchi Organic',
    service: 'performance_marketing',
    budget: 22000,
    status: 'lost',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 68,
    source: 'Public Web Capture',
    notesCount: 2,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_117',
    name: 'Virat Kohli',
    email: 'vk@one8.com',
    phone: '+91 91919 91919',
    company: 'One8 Foundation',
    service: 'web_dev',
    budget: 45000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 85,
    source: 'LinkedIn Outbound',
    notesCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_118',
    name: 'Alia Bhatt',
    email: 'alia@edamamma.in',
    phone: '+91 70707 70707',
    company: 'Ed-a-Mamma',
    service: 'shopify_dev',
    budget: 65000,
    status: 'discovery',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 92,
    source: 'Referral',
    notesCount: 1,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_119',
    name: 'Ranbir Kapoor',
    email: 'rk@saavn.com',
    phone: '+91 80808 80808',
    company: 'Saavn Media',
    service: 'cro_audit',
    budget: 35000,
    status: 'qualified',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 77,
    source: 'Inbound Contact',
    notesCount: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_120',
    name: 'Anushka Sharma',
    email: 'anushka@nush.in',
    phone: '+91 60606 60606',
    company: 'Nush Clothing',
    service: 'shopify_dev',
    budget: 55000,
    status: 'contacted',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 88,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  }
];`;

const updated = content.replace(/updatedAt: new Date\(Date\.now\(\) - 10 \* 24 \* 60 \* 60 \* 1000\)\.toISOString\(\),\n  },/, `updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),\n  }${extraLeads}`);

fs.writeFileSync('./server/store.ts', updated);
