const fs = require('fs');
const content = fs.readFileSync('./server/store.ts', 'utf8');

const extraLeads = `,
  {
    id: 'lead_121',
    name: 'Diljit Dosanjh',
    email: 'diljit@urbanpendu.com',
    phone: '+91 90000 12345',
    company: 'Urban Pendu Music',
    service: 'performance_marketing',
    budget: 45000,
    status: 'new',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 80,
    source: 'LinkedIn Outbound',
    notesCount: 0,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_122',
    name: 'Priyanka Chopra',
    email: 'pc@anomaly.com',
    phone: '+1 (555) 777-8888',
    company: 'Anomaly Haircare',
    service: 'shopify_dev',
    budget: 120000,
    status: 'discovery',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 95,
    source: 'Referral',
    notesCount: 2,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_123',
    name: 'Shah Rukh Khan',
    email: 'srk@redchillies.com',
    phone: '+91 88888 22222',
    company: 'Red Chillies VFX',
    service: 'web_dev',
    budget: 200000,
    status: 'qualified',
    assignedToId: 'usr_admin_1',
    assignedToName: 'Priya Sharma',
    score: 99,
    source: 'Inbound Contact',
    notesCount: 3,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_124',
    name: 'Deepika Padukone',
    email: 'dp@82e.com',
    phone: '+91 77777 33333',
    company: '82°E Skincare',
    service: 'cro_audit',
    budget: 30000,
    status: 'contacted',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 85,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_125',
    name: 'Salman Khan',
    email: 'sk@beinghuman.com',
    phone: '+91 99999 44444',
    company: 'Being Human',
    service: 'shopify_dev',
    budget: 80000,
    status: 'negotiation',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 88,
    source: 'Event Booth',
    notesCount: 4,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_126',
    name: 'Kareena Kapoor',
    email: 'bebo@gorgeous.in',
    phone: '+91 88888 55555',
    company: 'Kareena Style',
    service: 'performance_marketing',
    budget: 25000,
    status: 'won',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 90,
    source: 'Referral',
    notesCount: 2,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_127',
    name: 'Hrithik Roshan',
    email: 'hrx@hrxbrand.com',
    phone: '+91 77777 66666',
    company: 'HRX Activewear',
    service: 'full_stack_build',
    budget: 95000,
    status: 'proposal',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 92,
    source: 'Inbound Contact',
    notesCount: 5,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_128',
    name: 'Katrina Kaif',
    email: 'kat@kaybeauty.in',
    phone: '+91 99999 77777',
    company: 'Kay Beauty',
    service: 'cro_audit',
    budget: 18000,
    status: 'lost',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 65,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_129',
    name: 'Ayushmann Khurrana',
    email: 'ak@urbanclap.com',
    phone: '+91 88888 88888',
    company: 'Urban Company',
    service: 'web_dev',
    budget: 50000,
    status: 'qualified',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 82,
    source: 'LinkedIn Outbound',
    notesCount: 2,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_130',
    name: 'Vicky Kaushal',
    email: 'vicky@mensxp.com',
    phone: '+91 77777 99999',
    company: 'MensXP Grooming',
    service: 'shopify_dev',
    budget: 35000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 78,
    source: 'Referral',
    notesCount: 0,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  }
];`;

const updated = content.replace("id: 'lead_120',\n    name: 'Anushka Sharma',\n    email: 'anushka@nush.in',\n    phone: '+91 60606 60606',\n    company: 'Nush Clothing',\n    service: 'shopify_dev',\n    budget: 55000,\n    status: 'contacted',\n    assignedToId: 'usr_member_1',\n    assignedToName: 'Rahul Patel',\n    score: 88,\n    source: 'Public Web Capture',\n    notesCount: 1,\n    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),\n    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),\n  }", "id: 'lead_120',\n    name: 'Anushka Sharma',\n    email: 'anushka@nush.in',\n    phone: '+91 60606 60606',\n    company: 'Nush Clothing',\n    service: 'shopify_dev',\n    budget: 55000,\n    status: 'contacted',\n    assignedToId: 'usr_member_1',\n    assignedToName: 'Rahul Patel',\n    score: 88,\n    source: 'Public Web Capture',\n    notesCount: 1,\n    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),\n    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),\n  }" + extraLeads);

fs.writeFileSync('./server/store.ts', updated);
