import { Lead, LeadActivity, LeadNote, LeadService, LeadStatus, PipelineStats, User, EmailLog } from '../src/types';

// Initial pre-seeded users
export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin_1',
    name: 'Sujal Das',
    email: 'Sujal.das8797@gmail.com',
    role: 'admin',
    avatar: 'https://kommodo.ai/i/39Vh61G4xzFg3t1OpWed',
    title: 'Head of Sales & Growth',
    active: true,
  },
  {
    id: 'usr_member_1',
    name: 'Rahul Patel',
    email: 'rahul@leadtracker.app',
    role: 'member',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    title: 'Senior Account Executive',
    active: true,
  },
  {
    id: 'usr_member_2',
    name: 'Ananya Singh',
    email: 'ananya@leadtracker.app',
    role: 'member',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    title: 'Technical Sales Specialist',
    active: true,
  },
  {
    id: 'usr_member_3',
    name: 'Vikram Gupta',
    email: 'vikram@leadtracker.app',
    role: 'member',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    title: 'Business Development Rep',
    active: true,
  },
];

// Helper to compute lead score (0-100) based on budget, service, and data completeness
export function calculateLeadScore(budget: number, service: LeadService, phone: boolean, company: string): number {
  let score = 30; // base score
  if (budget >= 50000) score += 35;
  else if (budget >= 25000) score += 25;
  else if (budget >= 10000) score += 15;
  else if (budget >= 5000) score += 10;

  if (service === 'full_stack_build' || service === 'shopify_dev') score += 15;
  else if (service === 'performance_marketing') score += 10;

  if (phone) score += 10;
  if (company && company.length > 3) score += 10;

  return Math.min(100, Math.max(10, score));
}

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_101',
    name: 'Rohan Desai',
    email: 'marcus@luminaapparel.com',
    phone: '+1 (555) 234-5678',
    company: 'Lumina Apparel US',
    service: 'shopify_dev',
    budget: 45000,
    status: 'negotiation',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 85,
    source: 'Public Web Capture',
    notesCount: 3,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_102',
    name: 'Kavya Reddy',
    email: 'elena@nordicwellness.co.uk',
    phone: '+44 20 7946 0912',
    company: 'Nordic Wellness UK',
    service: 'full_stack_build',
    budget: 65000,
    status: 'proposal',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 95,
    source: 'Inbound Contact',
    notesCount: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_103',
    name: 'Arjun Kumar',
    email: 'david@apexlogistics.au',
    phone: '+61 2 9876 5432',
    company: 'Apex Logistics AU',
    service: 'web_dev',
    budget: 28000,
    status: 'discovery',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 70,
    source: 'LinkedIn Outbound',
    notesCount: 1,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_104',
    name: 'Neha Verma',
    email: 'chloe@velourcosmetics.com',
    phone: '+1 (555) 890-1234',
    company: 'Velour Beauty',
    service: 'performance_marketing',
    budget: 18000,
    status: 'contacted',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 60,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_105',
    name: 'Aditya Joshi',
    email: 'liam@dublingear.ie',
    phone: '+353 1 496 0123',
    company: 'Dublin Outdoor Gear',
    service: 'cro_audit',
    budget: 12000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 50,
    source: 'Public Web Capture',
    notesCount: 0,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_106',
    name: 'Riya Kapoor',
    email: 'sophia@sterlingfintech.io',
    phone: '+1 (555) 432-1098',
    company: 'Sterling Pay Systems',
    service: 'full_stack_build',
    budget: 85000,
    status: 'won',
    assignedToId: 'usr_admin_1',
    assignedToName: 'Priya Sharma',
    score: 98,
    source: 'Referral',
    notesCount: 4,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_107',
    name: 'Karan Malhotra',
    email: 'jason@craftbrewco.com',
    phone: '+1 (555) 765-4321',
    company: 'Craft Brew Collective',
    service: 'shopify_dev',
    budget: 15000,
    status: 'lost',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 40,
    source: 'Public Web Capture',
    notesCount: 2,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_108',
    name: 'Aisha Mehta',
    email: 'aisha@techwave.io',
    phone: '+91 98765 43210',
    company: 'TechWave Solutions',
    service: 'full_stack_build',
    budget: 55000,
    status: 'qualified',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 85,
    source: 'Referral',
    notesCount: 1,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_109',
    name: 'Ravi Teja',
    email: 'ravi@krishifarms.in',
    phone: '+91 91234 56789',
    company: 'Krishi AgriTech',
    service: 'web_dev',
    budget: 32000,
    status: 'qualified',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 75,
    source: 'Inbound Contact',
    notesCount: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_110',
    name: 'Sunil Gavaskar',
    email: 'sunil@pitchperfect.io',
    phone: '+44 20 8123 4567',
    company: 'Pitch Perfect',
    service: 'shopify_dev',
    budget: 70000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 90,
    source: 'Public Web Capture',
    notesCount: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_111',
    name: 'Tara Singh',
    email: 'tara@boutiquehotels.in',
    phone: '+91 88888 99999',
    company: 'Heritage Stays',
    service: 'performance_marketing',
    budget: 15000,
    status: 'contacted',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 65,
    source: 'LinkedIn Outbound',
    notesCount: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_112',
    name: 'Suresh Raina',
    email: 'suresh@athleticgear.com',
    phone: '+1 (555) 345-6789',
    company: 'Athletic Gear Pro',
    service: 'cro_audit',
    budget: 25000,
    status: 'discovery',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 72,
    source: 'Event Booth',
    notesCount: 2,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_113',
    name: 'Smriti Mandhana',
    email: 'smriti@womeninbiz.org',
    phone: '+91 99999 11111',
    company: 'WIB Network',
    service: 'web_dev',
    budget: 40000,
    status: 'proposal',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 82,
    source: 'Referral',
    notesCount: 3,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_114',
    name: 'Prakash Raj',
    email: 'prakash@cinemaarts.co',
    phone: '+44 7700 900123',
    company: 'Cinema Arts Studio',
    service: 'shopify_dev',
    budget: 28000,
    status: 'negotiation',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 78,
    source: 'Inbound Contact',
    notesCount: 4,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_115',
    name: 'Divya Bharti',
    email: 'divya@glamourmag.in',
    phone: '+91 77777 66666',
    company: 'Glamour Magazine',
    service: 'full_stack_build',
    budget: 90000,
    status: 'won',
    assignedToId: 'usr_admin_1',
    assignedToName: 'Priya Sharma',
    score: 99,
    source: 'Referral',
    notesCount: 5,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_116',
    name: 'M.S. Dhoni',
    email: 'mahi@ranchifarms.com',
    phone: '+91 81818 81818',
    company: 'Ranchi Organic',
    service: 'performance_marketing',
    budget: 22000,
    status: 'lost',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 68,
    source: 'Public Web Capture',
    notesCount: 2,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_117',
    name: 'Virat Kohli',
    email: 'vk@one8.com',
    phone: '+91 91919 91919',
    company: 'One8 Foundation',
    service: 'web_dev',
    budget: 45000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 85,
    source: 'LinkedIn Outbound',
    notesCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_118',
    name: 'Alia Bhatt',
    email: 'alia@edamamma.in',
    phone: '+91 70707 70707',
    company: 'Ed-a-Mamma',
    service: 'shopify_dev',
    budget: 65000,
    status: 'discovery',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 92,
    source: 'Referral',
    notesCount: 1,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_119',
    name: 'Ranbir Kapoor',
    email: 'rk@saavn.com',
    phone: '+91 80808 80808',
    company: 'Saavn Media',
    service: 'cro_audit',
    budget: 35000,
    status: 'qualified',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 77,
    source: 'Inbound Contact',
    notesCount: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_120',
    name: 'Anushka Sharma',
    email: 'anushka@nush.in',
    phone: '+91 60606 60606',
    company: 'Nush Clothing',
    service: 'shopify_dev',
    budget: 55000,
    status: 'contacted',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 88,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_121',
    name: 'Diljit Dosanjh',
    email: 'diljit@urbanpendu.com',
    phone: '+91 90000 12345',
    company: 'Urban Pendu Music',
    service: 'performance_marketing',
    budget: 45000,
    status: 'new',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 80,
    source: 'LinkedIn Outbound',
    notesCount: 0,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_122',
    name: 'Priyanka Chopra',
    email: 'pc@anomaly.com',
    phone: '+1 (555) 777-8888',
    company: 'Anomaly Haircare',
    service: 'shopify_dev',
    budget: 120000,
    status: 'discovery',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 95,
    source: 'Referral',
    notesCount: 2,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_123',
    name: 'Shah Rukh Khan',
    email: 'srk@redchillies.com',
    phone: '+91 88888 22222',
    company: 'Red Chillies VFX',
    service: 'web_dev',
    budget: 200000,
    status: 'qualified',
    assignedToId: 'usr_admin_1',
    assignedToName: 'Priya Sharma',
    score: 99,
    source: 'Inbound Contact',
    notesCount: 3,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_124',
    name: 'Deepika Padukone',
    email: 'dp@82e.com',
    phone: '+91 77777 33333',
    company: '82°E Skincare',
    service: 'cro_audit',
    budget: 30000,
    status: 'contacted',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 85,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_125',
    name: 'Salman Khan',
    email: 'sk@beinghuman.com',
    phone: '+91 99999 44444',
    company: 'Being Human',
    service: 'shopify_dev',
    budget: 80000,
    status: 'negotiation',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 88,
    source: 'Event Booth',
    notesCount: 4,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_126',
    name: 'Kareena Kapoor',
    email: 'bebo@gorgeous.in',
    phone: '+91 88888 55555',
    company: 'Kareena Style',
    service: 'performance_marketing',
    budget: 25000,
    status: 'won',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 90,
    source: 'Referral',
    notesCount: 2,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_127',
    name: 'Hrithik Roshan',
    email: 'hrx@hrxbrand.com',
    phone: '+91 77777 66666',
    company: 'HRX Activewear',
    service: 'full_stack_build',
    budget: 95000,
    status: 'proposal',
    assignedToId: 'usr_member_3',
    assignedToName: 'Vikram Gupta',
    score: 92,
    source: 'Inbound Contact',
    notesCount: 5,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_128',
    name: 'Katrina Kaif',
    email: 'kat@kaybeauty.in',
    phone: '+91 99999 77777',
    company: 'Kay Beauty',
    service: 'cro_audit',
    budget: 18000,
    status: 'lost',
    assignedToId: 'usr_member_1',
    assignedToName: 'Rahul Patel',
    score: 65,
    source: 'Public Web Capture',
    notesCount: 1,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_129',
    name: 'Ayushmann Khurrana',
    email: 'ak@urbanclap.com',
    phone: '+91 88888 88888',
    company: 'Urban Company',
    service: 'web_dev',
    budget: 50000,
    status: 'qualified',
    assignedToId: 'usr_member_2',
    assignedToName: 'Ananya Singh',
    score: 82,
    source: 'LinkedIn Outbound',
    notesCount: 2,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead_130',
    name: 'Vicky Kaushal',
    email: 'vicky@mensxp.com',
    phone: '+91 77777 99999',
    company: 'MensXP Grooming',
    service: 'shopify_dev',
    budget: 35000,
    status: 'new',
    assignedToId: null,
    assignedToName: null,
    score: 78,
    source: 'Referral',
    notesCount: 0,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_NOTES: LeadNote[] = [
  {
    id: 'note_1',
    leadId: 'lead_101',
    authorId: 'usr_admin_1',
    authorName: 'Priya Sharma',
    authorRole: 'admin',
    content: 'Initial discovery call completed. Rohan wants custom Shopify Plus theme rebuild with subscriptions integration.',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'note_2',
    leadId: 'lead_101',
    authorId: 'usr_member_1',
    authorName: 'Rahul Patel',
    authorRole: 'member',
    content: 'Sent revised commercial proposal (₹45k milestone-based). COO requested tech stack review with in-house dev.',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'note_3',
    leadId: 'lead_102',
    authorId: 'usr_member_2',
    authorName: 'Ananya Singh',
    authorRole: 'member',
    content: 'Technical scope review: full-stack custom headless store with Next.js & Shopify Storefront API.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    id: 'act_1',
    leadId: 'lead_101',
    userId: 'usr_admin_1',
    userName: 'Priya Sharma',
    action: 'Lead Captured',
    details: 'Submitted public lead capture form for Shopify Development (₹45,000 budget)',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_2',
    leadId: 'lead_101',
    userId: 'usr_admin_1',
    userName: 'Priya Sharma',
    action: 'Assigned Lead',
    details: 'Assigned lead to Rahul Patel (Senior Account Executive)',
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_3',
    leadId: 'lead_101',
    userId: 'usr_member_1',
    userName: 'Rahul Patel',
    action: 'Stage Changed',
    details: 'Moved pipeline stage from "Discovery Call" to "Negotiation"',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// In-Memory Database State
class DataStore {
  users: User[] = [...INITIAL_USERS];
  leads: Lead[] = [...INITIAL_LEADS];
  notes: LeadNote[] = [...INITIAL_NOTES];
  activities: LeadActivity[] = [...INITIAL_ACTIVITIES];
  emails: EmailLog[] = [];

  reset() {
    this.users = JSON.parse(JSON.stringify(INITIAL_USERS));
    this.leads = JSON.parse(JSON.stringify(INITIAL_LEADS));
    this.notes = JSON.parse(JSON.stringify(INITIAL_NOTES));
    this.activities = JSON.parse(JSON.stringify(INITIAL_ACTIVITIES));
    this.emails = [];
  }

  logEmail(leadId: string, leadCompany: string, recipient: string, subject: string, body: string) {
    const email: EmailLog = {
      id: `email_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      leadId,
      leadCompany,
      recipient,
      subject,
      body,
      timestamp: new Date().toISOString(),
    };
    this.emails.unshift(email);
    return email;
  }

  logActivity(leadId: string, userId: string, userName: string, action: string, details: string) {
    const act: LeadActivity = {
      id: `act_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      leadId,
      userId,
      userName,
      action,
      details,
      timestamp: new Date().toISOString(),
    };
    this.activities.unshift(act);
    return act;
  }
}

export const db = new DataStore();
